"""empty message

Revision ID: 49527deeab7a
Revises: 23042843bc4d
Create Date: 2025-03-06 22:50:49.090685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49527deeab7a'
down_revision = '23042843bc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
